SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM ONLINE_SALE AS SALE
LEFT JOIN USER_INFO AS INFO
    On SALE.USER_ID = INFO.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER