SELECT MONTH(START_DATE) AS MONTH, HIS.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
INNER JOIN (
    SELECT CAR_ID, COUNT(*) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) IN (8, 9, 10)
    GROUP BY CAR_ID
) SUB_HIS
ON SUB_HIS.CAR_ID = HIS.CAR_ID
WHERE SUB_HIS.CNT >= 5
    AND YEAR(START_DATE) = 2022
    AND MONTH(START_DATE) IN (8, 9, 10)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH,CAR_ID DESC;