SELECT pro.PRODUCT_CODE, pro.PRICE * SUM(offs.SALES_AMOUNT) AS SALES
FROM PRODUCT AS pro
LEFT JOIN OFFLINE_SALE AS offs
    ON pro.PRODUCT_ID = offs.PRODUCT_ID
GROUP BY pro.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;