SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(PRO.PRICE * ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRO
LEFT JOIN FOOD_ORDER AS ORD
    ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE ORD.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID