SELECT REV.REST_ID, INF.REST_NAME, INF.FOOD_TYPE, INF.FAVORITES, INF.ADDRESS, ROUND(AVG(REV.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS REV
LEFT JOIN REST_INFO AS INF
    ON REV.REST_ID = INF.REST_ID
GROUP BY REV.REST_ID
HAVING INF.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, INF.FAVORITES DESC
